name: Sync Snowflake Repo

on:
  push:
    branches:
      - master

jobs:
  update-snowflake:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install Snowflake Connector
        run: pip install snowflake-connector-python

      - name: Run Fetch Command
        env:
          SNOWFLAKE_ACCOUNT: ${{ secrets.SNOWFLAKE_ACCOUNT }}
          SNOWFLAKE_USER: ${{ secrets.SNOWFLAKE_USER }}
          SNOWFLAKE_PASSWORD: ${{ secrets.SNOWFLAKE_PASSWORD }}
          SNOW_WH: COMPUTE_WH
          SNOW_DB: KD_POC2_DB
          SNOW_SCHEMA: PUBLIC
        run: |
          python -c "
          import snowflake.connector
          import os

          print('Connecting to Snowflake...')
          conn = snowflake.connector.connect(
              user=os.environ['SNOWFLAKE_USER'],
              password=os.environ['SNOWFLAKE_PASSWORD'],
              account=os.environ['SNOWFLAKE_ACCOUNT'],
              warehouse=os.environ['SNOW_WH'],
              database=os.environ['SNOW_DB'],
              schema=os.environ['SNOW_SCHEMA']
          )

          print('Triggering Git Fetch...')
          conn.cursor().execute('ALTER GIT REPOSITORY my_dbt_repo FETCH')
          print('Success: Repo Updated!')
          conn.close()
          "
